folders:
   good_folder_name:
   - "_Good"
   - "_GOOD"
   - "Good"
   - "GOOD"
   - "good"
   all_folder_name:
   - "_all"
   - "_ALL"
   - "all"
   - "All"
   - "ALL"
   crt_folder_name:
   - "_DNG"
   - "DNG"
   - "crt"
   - "CRT"
   - "Crt"
   - "CRT"
blacklist:
  enabled: true
  location: "artifact\blacklist.txt"

file_extensions:
   crt:
   - ".crt"
   - ".dng"
   - ".raw"
   good:
   - ".jpg"